
title: Curiouser and Curiouser
author: Maxim Kropotov
description: > # this means to ignore newlines until "baseurl:"
               Adventures in the wonderland of software developement
baseurl: "" 
url: "https://undeadcat.github.io"
twitter_username: mkropotov
github_username:  undeadcat
highlighter: pygments
markdown: kramdown
